create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  summary text not null default '',
  status text not null default 'active' check (status in ('active', 'planning', 'archived')),
  project_type text not null default 'project' check (project_type in ('project', 'group')),
  featured boolean not null default false,
  cover_image_url text,
  body_markdown text not null default '',
  published boolean not null default true,
  parent_project_id bigint references public.projects(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null default '',
  event_at timestamptz not null,
  location text,
  cover_image_url text,
  body_markdown text not null default '',
  published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.dev_logs (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null default '',
  published_at timestamptz not null default timezone('utc', now()),
  cover_image_url text,
  body_markdown text not null default '',
  published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists projects_parent_project_id_idx
  on public.projects(parent_project_id);

create index if not exists projects_featured_idx
  on public.projects(featured);

create index if not exists events_event_at_idx
  on public.events(event_at);

create index if not exists dev_logs_published_at_idx
  on public.dev_logs(published_at);

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at
before update on public.events
for each row
execute function public.set_updated_at();

drop trigger if exists set_dev_logs_updated_at on public.dev_logs;
create trigger set_dev_logs_updated_at
before update on public.dev_logs
for each row
execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('content-media', 'content-media', true)
on conflict (id) do update
set public = excluded.public;
